server:
  port: 3001
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: Claps_test
  username: root
  password: 123456
  charset: utf8
github:
  ClientID: 365a426af206381a9344
  ClientSecret: c6a8e8c87f5f8353a488e920ce547ac9cece5a03
  ClientToken: 050ab195b63d4138dc60946c5d9e57969e920e3d
  OauthCallBack: http://localhost:3001/api/oauth
mixin:
  UserId: a39c3ffc-c308-4c12-b117-fb7410cdbb43
  PinCode: 184475
  SessionId: c2923ed3-486d-4355-89ce-c92b21b9c3ac
  PinToken: F0w4pc9g7oPSamuWS/yVOYNPZMMlU9LF33yWlhqcfeLUWdEem9pXleNIYG8Ir8An7rzmZ31bzFKqBBIa2yCUcYLj9uVT63MwLcqDbkR4qQMlADXhA0czrEkFPtCQw5jWF5P18MyfHTYPbJ7hEahpW/2gr54uCufwsbwxzSStERs=
  PrivateKey: |
   -----BEGIN RSA PRIVATE KEY-----
   MIICXAIBAAKBgQCXUgYxH+ryrx80Pt8KNREwp7ag+6dwF21Buz7wr+xlm8aIkwDu
   riQYa6SkDz+fi0dpAGKlFQGGuQni3u70qJnPXfM5FG4mrQ5zSTVtZyE1p5O+Z5oM
   eBGsKRPTW4notMRTvIbwumOinsoi/eANM3PGaJyEdcCP33Fyq7piggFwGwIDAQAB
   AoGBAIoPalrTtjcplBzE6BaWCFMOEdCbCk948FQylOBgghzKnb7p8MXT2Fb3j0Wo
   K/JSzxp8IYRgv/29QcnegMJ0Oa/Touez0ZblS4NBiE9DC6Vo+C0AbIRWmxZdOv81
   DDcMy00Vd0W2wKpq58ugtw/pIa+B2BnGZV2MtPuOdkJ8pGbBAkEAzQaBXf3fmp35
   xUgsXel+aXnx6fEvv1+HPS+LZVsFgtPQnGtxmoDB38A/DBDZYWPrsdKqgq7UB0rF
   bPl5HrGscQJBALzxSv9CU7LB9Ix7mPX9jBVyWs0HlqOmsRMr9TYSedW8CCCGhGHI
   jRK0RPVIbB6j4lY8nooETJARVlgmwuUEG0sCQAhf7KbfOOQC8fHqCc3oPL6oOYZ5
   0J57k3WfXI1OU4JNjqblCKXr/n9aRfkDMy30O+tulIJ0C7skhb32zsi/LzECQGW2
   P3lKa2Q/pTY7EwzZgR/Kf7b/7sgKZCi98TM6nvvATV+1Cm7ZV5hKExU393xHHQDv
   gSkrR0wHCURLGX/PxiECQA6HGCrBKi7hywibClGn11Q8qOBDia1mEysm823gmTXW
   mAvlrz+d1ClrUbJMdwGe9xXeFof9h/y8zE1FGjGWTtM=
   -----END RSA PRIVATE KEY-----