server:
  port: 3001
log:
#  filePath: ./logs/
#  fileName: test.log
  fileType: Stdout # Stdout or File
  level: DebugLevel # InfoLevel or DebugLevel or ErrorLevel or FatalLevel or PanicLevel or TraceLevel or WarnLevel
  formatter: json # text or json
gorm:
    logMode: true # true or false